services:
  - type: web
    name: secret-server
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: STORAGE_DIR
        value: /app/var/storage